"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--l^*e5@k#!*zc5tz9e+=bo$s06lu313p6_uxok$z(n+mk%!df4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'database',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # SQLAlchemy scoped session teardown - must wrap anything that queries,
    # otherwise the scoped session leaks state between requests.
    'middleware.db_session.DbSessionMiddleware',
    # Request/response logger, writes to Logs.txt.
    'middleware.Middleware.SimpleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = 'none'

# Repository errors become HTTP status codes here.
# Deny by default: no token, no data.
# Public views opt out with permission_classes = [AllowAny].
# dj_rest_auth login and registration already do.
# JWTCookieAuthentication reads Bearer header or access cookie.
# TokenAuthentication covers authtoken keys.
# SessionAuthentication omitted: it would enforce CSRF on every call.
# That does NOT make the API CSRF-proof. JWTCookieAuthentication also
# authenticates off the 'access' cookie, and JWT_AUTH_COOKIE_USE_CSRF
# defaults to False. What blocks cross-site writes today is
# JWT_AUTH_SAMESITE defaulting to 'Lax'. If that is ever set to 'None'
# for a cross-origin SPA, turn on JWT_AUTH_COOKIE_USE_CSRF in REST_AUTH.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'mysite.exceptions.repository_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'swagger.common.PathParameterSchema',
}

ROOT_URLCONF = 'mysite.urls'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Brand Scheduling API',
    'DESCRIPTION': (
        'Shift scheduling across brands. A brand employs people through Jobs, '
        'opens a Schedule, and fills it with Roles; each Role holds Shifts, '
        'which are created unstaffed and staffed by a later PUT once the '
        'employee is eligible and free.\n\n'
        'Two conventions worth knowing before reading the operations below:\n\n'
        '- Dates accept `D/M/YYYY` as well as ISO `YYYY-MM-DD`, and times '
        'accept bare integer hours, so `8` means 08:00. Body keys are matched '
        'case-insensitively and several have aliases, noted per field.\n'
        '- The two failure shapes differ: a 400 answers `{"error": "..."}` '
        'while a 404 answers `{"detail": "..."}`.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Same MySQL database as database/engine.py.
# Same env vars, so both stacks stay aligned.
# Django's tables sit beside the SQLAlchemy ones.
# No foreign keys cross between the two ORMs.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'Schedule'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', '2252'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh',
    'JWT_AUTH_HTTPONLY': True,
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
