"""URL configuration for mysite project.

Everything under ``api/v1/`` is generated by routers - no endpoint here is a
hand-written ``path()``. The single ``path()`` in the API tree is the mount
point that gives the whole router tree its version prefix, because a prefix
shared by several sibling routers cannot come from a router itself.

The routers are defined below, with two departures from the DRF defaults, both
forced by the endpoint list:

* ``trailing_slash`` is off, matching the ``/auth/`` convention. With
  ``APPEND_SLASH`` on, a POST to the slash-suffixed spelling 301s and drops its
  body, so the slash-less URL has to be the canonical one.
* The list route also accepts ``PUT``, mapped to ``update``. The shift upsert
  is addressed by ``(role, employee, date)`` rather than by a shift pk, so it
  has no id to put in the URL and has to act on the collection.

Everything else is the stock behaviour.
"""
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from rest_framework_nested import routers as nested_routers
from django.urls import path, include


from mysite.views import (
    BrandViewSet,
    EmployeeTimeViewSet,
    EmployeeViewSet,
    RoleViewSet,
    ScheduleViewSet,
    ShiftViewSet,
)


# ------------------------------------------------------------------- routers


def _collection_put_routes(routes):
    """Copy ``routes`` with ``PUT`` added to the list route's mapping."""
    patched = []
    for route in routes:
        if isinstance(route, routers.Route) and route.mapping.get("get") == "list":
            mapping = dict(route.mapping)
            mapping.setdefault("put", "update")
            route = route._replace(mapping=mapping)
        patched.append(route)
    return patched


class SlashlessRouter(routers.DefaultRouter):
    """Top-level router: no trailing slash, collection-level PUT allowed."""

    routes = _collection_put_routes(routers.DefaultRouter.routes)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("trailing_slash", False)
        super().__init__(*args, **kwargs)


class SlashlessNestedRouter(nested_routers.NestedDefaultRouter):
    """The nested equivalent, so the whole tree behaves identically."""

    routes = _collection_put_routes(nested_routers.NestedDefaultRouter.routes)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("trailing_slash", False)
        super().__init__(*args, **kwargs)


# ---------------------------------------------------------------- top level
router = SlashlessRouter()
router.register('employees', EmployeeViewSet, basename='employees')
router.register('brands', BrandViewSet, basename='brands')

# Registered before 'schedules' so the literal wins.
# Unnested roles only ever answer with 400.
router.register('schedules/roles', RoleViewSet, basename='roles')

router.register('schedules', ScheduleViewSet, basename='schedules')

# ----------------------------------------------------------- brands/<id>/...
brands_router = SlashlessNestedRouter(router, 'brands', lookup='brand')
brands_router.register('employees', EmployeeViewSet, basename='brand-employees')
brands_router.register('schedules', ScheduleViewSet, basename='brand-schedules')

brand_schedules_router = SlashlessNestedRouter(
    brands_router, 'schedules', lookup='schedule'
)
brand_schedules_router.register('roles', RoleViewSet, basename='brand-schedule-roles')

# -------------------------------------------------------- schedules/<id>/...
schedules_router = SlashlessNestedRouter(router, 'schedules', lookup='schedule')
schedules_router.register('roles', RoleViewSet, basename='schedule-roles')
schedules_router.register('shifts', ShiftViewSet, basename='schedule-shifts')

# Deepest chain: shift create and the PUT upsert.
schedule_roles_router = SlashlessNestedRouter(schedules_router, 'roles', lookup='role')
schedule_roles_router.register('shifts', ShiftViewSet, basename='schedule-role-shifts')

# -------------------------------------------------------- employees/<id>/...
employees_router = SlashlessNestedRouter(router, 'employees', lookup='employee')
employees_router.register('shifts', ShiftViewSet, basename='employee-shifts')
employees_router.register('times', EmployeeTimeViewSet, basename='employee-times')
employees_router.register('schedules', ScheduleViewSet, basename='employee-schedules')

employee_schedules_router = SlashlessNestedRouter(
    employees_router, 'schedules', lookup='schedule'
)
employee_schedules_router.register(
    'shifts', ShiftViewSet, basename='employee-schedule-shifts'
)

api_v1_urls = (
    router.urls
    + brands_router.urls
    + brand_schedules_router.urls
    + schedules_router.urls
    + schedule_roles_router.urls
    + employees_router.urls
    + employee_schedules_router.urls
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(api_v1_urls)),
    path('api/v1/auth/', include('dj_rest_auth.urls')),
    path('api/v1/auth/registration/', include('dj_rest_auth.registration.urls')),
]
